# Generated by Django 5.1.1 on 2024-10-06 19:30

import datetime
import django.db.models.deletion
import django.db.models.expressions
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_type', models.CharField(choices=[('DOC', 'Document'), ('IMG', 'Image'), ('TXT', 'Text'), ('PDF', 'Pdf'), ('VID', 'Video'), ('AUD', 'Audio')], default='TXT', max_length=3)),
                ('chunk_size', models.FloatField(default=0.0)),
                ('chunk_hash', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=11)),
                ('quota_limit', models.DecimalField(decimal_places=1, default=300.0, max_digits=4)),
                ('quota_used', models.DecimalField(decimal_places=1, default=0.0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('PHO', 'Phone'), ('TAB', 'Tablet'), ('LAB', 'Laptop'), ('DSK', 'Desktop'), ('OTH', 'Other')], default='OTH', max_length=3)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive.cuser')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=255)),
                ('file_hash', models.CharField(max_length=64)),
                ('file_type', models.CharField(choices=[('DOC', 'Document'), ('IMG', 'Image'), ('TXT', 'Text'), ('PDF', 'Pdf'), ('VID', 'Video'), ('AUD', 'Audio')], default='TXT', max_length=3)),
                ('file_size', models.FloatField(default=0.0)),
                ('is_folder', models.BooleanField(db_default=False)),
                ('created_since', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive.cuser')),
            ],
        ),
        migrations.CreateModel(
            name='FileContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_order', models.IntegerField(db_default=1)),
                ('chunk_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive.chunk')),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive.file')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive.cuser')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive.group')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive.cuser')),
            ],
        ),
        migrations.CreateModel(
            name='SyncService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_since', models.DateTimeField(db_default=django.db.models.functions.datetime.Now())),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive.device')),
            ],
        ),
        migrations.CreateModel(
            name='Trash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due', models.DateTimeField(db_default=django.db.models.expressions.CombinedExpression(django.db.models.functions.datetime.Now(), '+', models.Value(datetime.timedelta(days=5))))),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drive.file')),
            ],
        ),
    ]
